---
- name: Actualizar caché APT
  apt:
    update_cache: yes

- name: Instalar Apache
  package:
    name: apache2
    state: present

- name: Iniciar y habilitar Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Mostrar usuario autenticado
  debug:
    msg: "Usuario autenticado: {{ ansible_user }}"

- name: Mostrar password (Vault test real)
  debug:
    msg: "Clave Vault: {{ ansible_password }}"
