---
- name: Instalar Apache
  package:
    name: apache2
    state: present

- name: Iniciar y habilitar el servicio Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Mostrar usuario autenticado (Vault test)
  debug:
    msg: "Usuario autenticado: {{ ansible_user }}"
